config/routes.rb
Accelr8::Application.routes.draw do

  resources :accelerators do
  end
  match 'accelerators/terms' => 'accelerators#terms', :via => :post
  match '/home' => 'accelerators#home', :as => 'home'

  devise_for :accelerator_users
  devise_for :users

  match '/accelerator_user_root', :to => 'accelerators#index'
  match '/accelerators' => 'accelerators#index', :as => :accelerator_user_root

  match '/user_root', :to => 'accelerators#index'

  match '/about' => 'acpages#about', :as => 'about'
  match '/beta' => 'acpages#beta', :as => 'beta'

  resources :questionnaires do
    resources :qfounders
    member do
      get 'apply'
    end
  end

  resources :ac_registrations, :only => [:index]
  match 'ac_registrations/testemail' => 'ac_registrations#testemail', :via => :post
  match 'ac_registrations/createbatch' => 'ac_registrations#createbatch', :via => :post
  match 'ac_registrations/destroybatch' => 'ac_registrations#destroybatch', :via => :delete

  root :to => "accelerators#home"

end

app/models/accelerator.rb
class Accelerator < ActiveRecord::Base
  belongs_to :accelerator_user
  has_many :ac_registrations, :dependent => :destroy

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name,	:presence => true
  validates :city,	:presence => true
  validates :state,	:presence => true
  validates :startdate,	:presence => true
  validates :duedate,	:presence => true
  validates :length,	:presence => true
  validates :website,	:format => /http/
  validates :lastname,	:presence => true
  validates :email,	:format => { :with => email_regex }
  validates :description,	:presence => true,
				:length => { :maximum => 300 }
  validates :acceptlate, :length => { :maximum => 100 }
# maximum should match _form.html.erb view

# validate do
#   errors.add(:base, "Application due date must be on or before start date") unless startdate >= duedate
# end

  validate :duedate_before_startdate

  def duedate_before_startdate
    errors.add(:base, "Application Due Date must be on or before Start Date") unless startdate >= duedate
  end

  def to_s
    if (self.season.nil? || self.season.empty?)
      self.name
    else
      self.name + " (" + self.season + ")"
    end
  end
end

app/controllers/accelerators_controller.rb
class AcceleratorsController < ApplicationController
  before_filter :authenticate_user!, :except => [:home]
  before_filter :authenticate_accelerator_user!, :except => [:index, :home]
# before_filter is_admin?

  # GET /accelerators
  # GET /accelerators.xml
  def index

    @sortcolumn = params[:column] ||= "startdate"
    @sortorder = params[:order] ||= "ASC"
    # sort columns by param
    @accelerators = Accelerator.where("izzaproved = ?", "yEs").order(@sortcolumn+" "+@sortorder)
    @userquest = Questionnaire.where(["user_id = ?", current_user]).last
#   @userquest is nil if Questionnaire not yet created for this user
#   what if no Questionnaire, Questionnaire.all = [] ?

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @accelerators }
    end
  end

  def home
    if user_signed_in?
      redirect_to accelerators_path
    else
      render :layout => false
    end
  end

  # GET /accelerators/1
  # GET /accelerators/1.xml
  def show
    @accelerator = Accelerator.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @accelerator }
    end
  end

  # GET /accelerators/1
  # GET /accelerators/1.xml
  def terms
    respond_to do |format|
      format.html # terms.html.erb
      format.xml  { head :ok }
    end
  end

  # GET /accelerators/new
  # GET /accelerators/new.xml
  def new
    @accelerator = Accelerator.new
    if accelerator_user_signed_in?
      @accelerator.email = current_accelerator_user.email
    end

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @accelerator }
    end
  end

  # GET /accelerators/1/edit
  def edit
    @accelerator = Accelerator.find(params[:id])
    if @accelerator.accelerator_user_id != current_accelerator_user.id
# cannot edit
      respond_to do |format|
        format.html { redirect_to accelerators_path }
#       format.html { redirect_to :back }
        format.xml  { head :ok }
      end
    end
  end

  # POST /accelerators
  # POST /accelerators.xml
  def create
    @accelerator = Accelerator.new(params[:accelerator])
    if accelerator_user_signed_in?
      @accelerator.accelerator_user_id = current_accelerator_user.id
      @accelerator.izzaproved = "yEs"
#   else if is_admin?
    end
# eventually admin will set izzaproved, default will be "nO"
# misspelled words more difficult for a hacker to find?
# izzaproved should not be visible from views

    respond_to do |format|
      if @accelerator.save
#       format.html { redirect_to(@accelerator, :notice => 'Accelerator was successfully created.') }
        format.html { redirect_to(accelerators_path, :notice => 'Accelerator was successfully created.') }
        format.xml  { render :xml => @accelerator, :status => :created, :location => @accelerator }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @accelerator.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /accelerators/1
  # PUT /accelerators/1.xml
  def update
    @accelerator = Accelerator.find(params[:id])

    did_update = nil
    if @accelerator.accelerator_user_id == current_accelerator_user.id
#   or is_admin?
# can update
      if @accelerator.update_attributes(params[:accelerator])
        did_update = :true
      end
    end

    respond_to do |format|
      if did_update == :true
#       format.html { redirect_to(@accelerator, :notice => 'Accelerator was successfully updated.') }
        format.html { redirect_to(accelerators_path, :notice => 'Accelerator was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @accelerator.errors, :status => :unprocessable_entity }
      end
    end
#   flash[:notice] = "accel update: " + params.inspect
  end

  # DELETE /accelerators/1
  # DELETE /accelerators/1.xml
  def destroy
    @accelerator = Accelerator.find(params[:id])

    respond_to do |format|
      if @accelerator.accelerator_user_id != current_accelerator_user.id
#   or is_admin?
# cannot destroy
#       format.html { redirect_to accelerators_path }
        format.html { redirect_to :back }
        format.xml  { head :ok }
      else
        @accelerator.destroy
        format.html { redirect_to(accelerators_url) }
#       format.html # index.html.erb
#       format.html { render :action => "index" }
        format.xml  { head :ok }
      end
    end
  end
end

app/helpers/accelerators_helper.rb
module AcceleratorsHelper
end

app/views/accelerators/_form.html.erb
<%= javascript_include_tag "http://www.google.com/jsapi" %>
<%= javascript_include_tag "jqueryref" %>
<%= javascript_include_tag "accel" %>

<%= form_for(@accelerator) do |f| %>
  <% if @accelerator.errors.any? %>
    <div id="error_explanation" class="clear">
      <h3 class="required"><%= pluralize(@accelerator.errors.count, "error") %> prohibited this accelerator from being saved:</h3>

      <ul>
      <% @accelerator.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table class="clear span-18">
    <tr class="accel nomargin">
      <td><%= f.label :name %><span class="required">*</span></td>
      <td><%= f.text_field :name %></td>
      <td><%= f.label :season, "Season / Year" %></td>
      <td><%= f.text_field :season, :size => 20 %></td>
    </tr>
    <tr class="accel nomargin">
      <td><%= f.label :city %><span class="required">*</span></td>
      <td><%= f.text_field :city %></td>
      <td><%= f.label :state, "State or Province" %><span class="required">*</span></td>
      <td><%= f.text_field :state, :size => 20 %></td>
    </tr>
    <tr class="accel nomargin">
      <td><%= f.label :country %></td>
      <td><%= f.text_field :country, :size => 30 %></td>
    </tr>
  </table>
  <table class="clear span-18">
    <tr class="accel nomargin even">
      <td><%= f.label :website %><span class="required">*</span></td>
      <td colspan=3><%= f.text_field :website, :size => 46 %></td>
    </tr>
  </table>
  <table class="clear span-18">
    <tr class="accel nomargin">
      <td><%= f.label :startdate, "Start Date" %><span class="required">*</span></td>
      <td>
        <%#= f.date_select :startdate, options = { :start_year => Time.now.year }, :class => "nomargin" %>
        <%= f.date_select :startdate, options = { :default => 7.days.from_now }, :class => "nomargin" %>
      </td>
      <td><%= f.label :length, "Length (weeks)" %><span class="required">*</span></td>
      <td><%= f.text_field :length, :size => 3 %></td>
    </tr>
    <tr class="accel nomargin">
      <td><%= f.label :duedate, "Application Due Date" %><span class="required">*</span></td>
      <td>
        <%#= f.date_select :duedate, options = { :start_year => Time.now.year }, :class => "nomargin" %>
        <%#= f.date_select :duedate, options = { :default => Time.now }, :class => "nomargin" %>
        <%= f.date_select :duedate, options = { :default => 0.days.from_now }, :class => "nomargin" %>
        <%#= f.date_select :duedate, options = { :default => -7.days.from_now }, :class => "nomargin" %>
        <%#= f.date_select :duedate, options = { :default => 7.days.ago }, :class => "nomargin" %>
      </td>
      <td/>
      <td/>
    </tr>
  </table>
  <table class="clear span-18">
    <tr class="accel nomargin">
      <td><b>Contact:</b><span class="required"> </span></td>
      <td class="nowrap"><%= f.label :firstname, "First name" %><span class="required"> </span></td>
      <td><%= f.text_field :firstname, :size => 15 %></td>
      <td class="nowrap"><%= f.label :lastname, "Last name" %><span class="required">*</span></td>
      <td><%= f.text_field :lastname, :size => 15 %></td>
    </tr>
    <tr class="accel nomargin">
      <td/>
      <td><%= f.label :email %><span class="required">*</span></td>
      <td colspan=4><%= f.text_field :email, :size => 57 %></td>
    </tr>
  </table>
  <table class="clear span-18">
    <tr class="accel">
      <td><%= f.label :description, "Description: Please describe the accelerator in 2 - 3 sentences." %><span class="required">*</span></td>
    </tr>
    <tr class="accel">
      <td>
        <%= f.text_area :description, :id => "dtext", :class => "bigarea charcount maxchar300" %>
      </td>
      <td><span id="dtext_ct" class="span-4 small dtextpad"></span>
      </td>
    </tr>
  </table>
  <table class="clear span-18">
    <tr class="accel">
      <td>
        <%= f.label :acceptlate, "We will accept late applications (Yes / No / Explain):" %>
      </td>
      <td>
        <%#= f.check_box :acceptlate, {}, "Yes", "No" %>
        <%= f.text_field :acceptlate, :size => 30, :maxlength => 100 %>
      </td>
    </tr>
    <!--tr class="accel">
      <td><%#= f.label :acceptemail, "Application email address (if different from contact email):" %></td>
      <td><%#= f.text_field :acceptemail, :size => 30 %></td>
    </tr>
    <tr class="accel">
      <td>
        <b>We have read the
        <%#= link_to "Terms of Agreement", { :controller => "accelerators", :action => "terms" }, :method => :post %>
        , and</b>
        <%#= f.label :acceptapp, "will accept emailed applications from Founders Hookup:" %>
       </td>
      <td>
        <br/>
        <%#= f.check_box :acceptapp, {}, "Yes", "No" %>
      </td>
    </tr!-->
  </table>
  <%#= f.hidden_field :acceptapp, :value => "No" %> <!-- rm for testing -->
  <div class="actions clear span-4">
    <%= f.submit %>
  </div>
<% end %>

app/views/accelerators/_list.html.erb
<%= form_for :ac_registration, :url => { :action => 'createbatch', :controller => 'ac_registrations' } do |f| %>

  <div class="field clear">
    <% quid = nil %>
    <% if ! @questionnaire.nil? %>
      <% quid = @questionnaire.id %>
    <% end %>
    <%= hidden_field_tag 'quid', quid %>
  </div>

  <% if @accelerators.any? %>

  <% col = @sortcolumn %>
  <% order = @sortorder=="DESC" ? "ASC" : "DESC" %>

  <table class="accel">
    <tr>
      <th class="index">
        <%= link_to 'Name', { :controller => "questionnaires", :action => "apply", :column => "name", :order => col=="name" ? order : "ASC" }, :method => :get, :class => col=="name" ? "hilite" : "" %>
      </th>
      <th class="index">
        <%= link_to 'Location', { :controller => "questionnaires", :action => "apply", :column => "city", :order => col=="city" ? order : "ASC" }, :method => :get, :class => col=="city" ? "hilite" : "" %>
      </th>
      <th class="index">
        <%= link_to 'Start Date', { :controller => "questionnaires", :action => "apply", :column => "startdate", :order => col=="startdate" ? order : "ASC" }, :method => :get, :class => col=="startdate" ? "hilite" : "" %>
      </th>
      <th class="index">
        <%= link_to 'Length', { :controller => "questionnaires", :action => "apply", :column => "length", :order => col=="length" ? order : "ASC" }, :method => :get, :class => col=="length" ? "hilite" : "" %>
      </th>
      <th class="index">
        Description
      </th>
      <th class="index center">
        <%= link_to 'Application Due Date', { :controller => "questionnaires", :action => "apply", :column => "duedate", :order => col=="duedate" ? order : "ASC" }, :method => :get, :class => col=="duedate" ? "hilite" : "" %>
      </th>
      <th class="index center">
        <%= link_to 'Accept Late Applications', { :controller => "questionnaires", :action => "apply", :column => "acceptlate", :order => col=="acceptlate" ? order : "ASC" }, :method => :get, :class => col=="acceptlate" ? "hilite" : "" %>
      </th>
      <th class="index center">Application<br/>Sent</th>
      <th class="index center">Apply<br/>Now</th>
    </tr>

    <% @accelerators.each do |accelerator| %>
    <tr>
      <td class="index">
        <%= link_to accelerator.to_s, accelerator.website, :title => accelerator.website, :target => "_blank" %>
      </td>
      <td class="index">
        <% if (accelerator.country.nil? || accelerator.country.empty?) %>
          <%= accelerator.city + ", " + accelerator.state %>
        <% else %>
          <%= accelerator.city + ", " + accelerator.state + ", " + accelerator.country %>
        <% end %>
      </td>
      <td class="index"><%= accelerator.startdate %></td>
      <td class="index"><span class="nowrap"><%= accelerator.length %> weeks</span></td>
      <td class="index description"><div class="info round">
        <%= accelerator.description %> ... <%= link_to " more", accelerator.website, :title => accelerator.website, :class => "more_link", :target => "_blank" %>
      </div></td>
      <td class="index center"><%= accelerator.duedate %></td>
      <td class="index center">
        <% if (accelerator.acceptlate.nil? || accelerator.acceptlate.empty?) %>
          No
        <% else %>
          <%= accelerator.acceptlate %>
        <% end %>
      </td>
      <td class="index center">
        <!-- don't need this column if email works? -->
        <%= AcRegistration.getlastmatch(quid, accelerator.id) %>
      </td>
      <td class="index center">
        <%# if accelerator.acceptapp == "Yes" %>
          <%= check_box_tag "bx[" + accelerator.id.to_s + "]", "", false %>
        <%# end %>
      </td>
    </tr>
    <% end %> <!-- accelerators.each -->
  </table>
  <% end %> <!-- accelerators.any? -->

  <% if @accelerators.any? %>
    <%= f.submit value='Submit Application', :class => "bigbutton right", :title => "Email application to selected accelerators" %>
  <% else %>
    <%= f.submit value='Submit Application', :disabled => true, :class => "bigbutton right" %>
  <% end %>

<% end %> <!-- form -->

app/views/accelerators/edit.html.erb
<div class="span-20">

<div class="span-6 bigfont bigmargin last">
  Update Accelerator
</div>

<%= render 'accelerator_users/shared/logout' %>

<%= render 'form' %>

<ul class="push-10 span-10 last">
  <li class="inline_menu">
    <%#= link_to 'List Accelerators', accelerators_path %>
    <%= link_to 'Discard Changes', accelerators_path %>
  </li>
  <li class="inline_menu">
    <%= link_to 'Delete Accelerator', { :controller => "accelerators", :action => "destroy" }, :confirm => 'Are you sure you want to delete this accelerator?', :method => :delete %>
  </li>
</ul>

</div>

app/views/accelerators/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Accelr8</title>
  <%#= stylesheet_link_tag :all %>
  <%#= stylesheet_link_tag 'scaffold' %>
  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
  <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
  <!--[if lt IE 8]>
    <%= stylesheet_link_tag 'blueprint/ie', :media => 'screen, projection' %>
  <![endif]-->
  <%= stylesheet_link_tag 'custom',  :media => 'screen' %>
  <%= stylesheet_link_tag 'accel',   :media => 'screen' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body class="homebox">

  <div style='width:10%; margin:20% 0 0 40%;'>
    <% logo = image_tag("ideaware/misc/fh_logo.png", :alt => "Founders Hookup",
                        :class => "fh_logo") %>
    <%= link_to logo, new_user_session_path, :title => "Click Here to Sign In" %>
  </div>

</body>
</html>

app/views/accelerators/index.html.erb
<div class="span-5 bigfont">
  Accelerator Directory
</div>

<% if @accelerators.any? %>

<div class="right">
  <% if ! @userquest.nil? %>
    <%= button_to 'Apply to Accelerators', { :controller => "questionnaires", :action => "show", :id => @userquest.id }, :method => :get, :class => "bigbutton" %>
  <% else %>
    <%= button_to 'Apply to Accelerators', { :controller => "questionnaires", :action => "new" }, :method => :get, :class => "bigbutton" %>
  <% end %>
</div>

<% end %>

<%= render 'accelerator_users/shared/logout' %>

<% if @accelerators.any? %>

<% col = @sortcolumn %>
<% order = @sortorder=="DESC" ? "ASC" : "DESC" %>

<table class="accel">
  <tr>
    <th class="index">
      <%= link_to 'Name', { :action => "index", :column => "name", :order => col=="name" ? order : "ASC" }, :method => :get, :class => col=="name" ? "hilite" : "" %>
    </th>
    <th class="index">
      <%= link_to 'Location', { :action => "index", :column => "city", :order => col=="city" ? order : "ASC" }, :method => :get, :class => col=="city" ? "hilite" : "" %>
    </th>
    <th class="index">
      <%= link_to 'Start Date', { :action => "index", :column => "startdate", :order => col=="startdate" ? order : "ASC" }, :method => :get, :class => col=="startdate" ? "hilite" : "" %>
    </th>
    <th class="index">
      <%= link_to 'Length', { :action => "index", :column => "length", :order => col=="length" ? order : "ASC" }, :method => :get, :class => col=="length" ? "hilite" : "" %>
    </th>
    <th class="index">Description</th>
    <th class="index center">
      <%= link_to 'Application Due Date', { :action => "index", :column => "duedate", :order => col=="duedate" ? order : "ASC" }, :method => :get, :class => col=="duedate" ? "hilite" : "" %>
    </th>
    <th class="index center">
      <%= link_to 'Accept Late Applications', { :action => "index", :column => "acceptlate", :order => col=="acceptlate" ? order : "ASC" }, :method => :get, :class => col=="acceptlate" ? "hilite" : "" %>
    </th>
    <!--th class="index center nowrap">
      <%#= link_to 'Accept Founders', { :action => "index", :column => "acceptapp"} %><br/>
      <%#= link_to 'Hookup Applications', { :action => "index", :column => "acceptapp"} %>
    </th!-->
    <th/>
  </tr>

  <% @accelerators.each do |accelerator| %>
  <tr>
    <td class="index">
      <% if accelerator.website.nil? || accelerator.website.empty? %>
        <%= accelerator.to_s %>
      <% else %>
        <%= link_to accelerator.to_s, accelerator.website, :title => accelerator.website, :target => "_blank" %>
      <% end %>
    </td>
    <td class="index">
      <% if (accelerator.country.nil? || accelerator.country.empty?) %>
        <%= accelerator.city + ", " + accelerator.state %>
      <% else %>
        <%= accelerator.city + ", " + accelerator.state + ", " + accelerator.country %>
      <% end %>
    </td>
    <td class="index"><%= accelerator.startdate %></td>
    <td class="index"><span class="nowrap"><%= accelerator.length %> weeks</span></td>
    <td class="index description"><div class="info round">
      <%= accelerator.description %>
      ... <%= link_to " more", accelerator.website, :title => accelerator.website, :class => "more_link", :target => "_blank" %>
    </div></td>
    <td class="index"><%= accelerator.duedate %></td>
    <td class="index center">
      <% if (accelerator.acceptlate.nil? || accelerator.acceptlate.empty?) %>
        No
      <% else %>
        <%= accelerator.acceptlate %>
      <% end %>
    </td>
    <!--td class="index center">
      <%# if (accelerator.acceptapp.nil? || accelerator.acceptapp.empty?) %>
        No
      <%# else %>
        <%#= accelerator.acceptapp %>
      <%# end %>
    </td!-->
    <td class="index">
      <%# if is_admin? || %>
      <% if (accelerator_user_signed_in? && (accelerator.accelerator_user_id == current_accelerator_user.id)) %>
        <%= button_to 'Edit', { :controller => "accelerators", :action => "edit", :id => accelerator.id }, :method => :get, :class => "small" %>
      <% end %>
    </td>
  </tr>
  <% end %>
</table>

<% else %>

  <p class="clear">No accelerators found.</p>

<% end %>

<%= render 'accelerator_users/shared/login' %>

<ul class="clear accel">
  <li class="nostyle">
    <%# if is_admin? || %>
    <% if accelerator_user_signed_in? && current_accelerator_user.accelerator.nil? %>
      <%= button_to 'Create New Accelerator', { :controller => "accelerators", :action => "new" }, :method => :get %>
    <% end %>
  </li>
</ul>

app/views/accelerators/new.html.erb
<div class='span-20'>

<div class="span-6 bigfont bigmargin last">
  Create New Accelerator
</div>

<%= render 'accelerator_users/shared/logout' %>

<%= render 'form' %>

<ul class="push-13 span-5 last">
  <li class="inline_menu">
    <%= link_to 'List Accelerators', accelerators_path %>
  </li>
</ul>

</div>

app/views/accelerators/show.html.erb
<h3>Accelerator Details</h3>

<p id="notice"><%= notice %></p>

<p>
  <% if (@accelerator.season.nil? || @accelerator.season.empty?) %>
    <b>Name:</b> <%= @accelerator.name %>
  <% else %>
    <b>Name:</b> <%= @accelerator.name + ", " %>
    <b> Season:</b> <%= @accelerator.season %>
  <% end %>
</p>

<p>
  <b>Web Site:</b>
  <%= link_to @accelerator.website, @accelerator.website %>
</p>

<p>
  <b>Location:</b>
  <% if (@accelerator.country.nil? || @accelerator.country.empty?) %>
    <%= @accelerator.city + ", " + @accelerator.state %>
  <% else %>
    <%= @accelerator.city + ", " + @accelerator.state + ", " + @accelerator.country %>
  <% end %>
</p>

<p>
  <b>Contact: Name:</b>
  <%= @accelerator.firstname + " " + @accelerator.lastname + ", " %>
  <b>Email:</b>
  <%= @accelerator.email  %>
</p>

<p>
  <b>Start Date:</b>
  <%= @accelerator.startdate %>
  <b> Length:</b>
  <%= @accelerator.length %> weeks
</p>

<p>
  <b>Application Due Date:</b>
  <%= @accelerator.duedate %>
</p>

<p>
  <b>We will accept late applications: </b>
  <% if (@accelerator.acceptlate.nil? || @accelerator.acceptlate.empty?) %>
     No
  <% else %>
    <%= @accelerator.acceptlate %>
  <% end %>
</p>

<p>
  <b>Description:</b>
  <%= @accelerator.description %>
</p>

<p>
  <b>Acceptance:<span> We will accept emailed applications from Founders Hookup: </span></b>
  <% if (@accelerator.acceptapp.nil? || @accelerator.acceptapp.empty?) %>
     No
  <% else %>
    <%= @accelerator.acceptapp %>
  <% end %>
</p>

<p>
  <b>Application Email Address (if different from contact email):</b>
  <%= @accelerator.acceptemail %>
</p>

<ul class="right">
  <li class="inline_menu">
    <%= link_to 'Edit Accelerator', edit_accelerator_path(@accelerator) %>
  </li>
  <li class="inline_menu">
    <%= link_to 'List Accelerators', accelerators_path %>
  </li>
</ul>

app/views/accelerators/terms.html.erb
<div class='span-20'>

<div class="span-14 bigfont bigmargin last">
  Accelerator Terms of Agreement
</div>

<div class="span-16 last">
  <p class="push-1">We, the Accelerator, agree to accept emailed applications from Founders Hookup, as is.  Founders Hookup makes no assurances as to the accuracy of statements made in applications.  Applications may contain forward-looking statements, and Founders Hookup cannot guarantee results.  
  </p>
  <p class="push-1 last">In addition, Founders Hookup makes no assurances as to the accuracy of information provided by Accelerators on the Founders Hookup web site.  Information presented by Accelerators may contain forward-looking statements, and Founders Hookup cannot guarantee results.  
  </p>
  <p>If you have any questions or concerns, please contact Founders Hookup at the email address or phone number below, and we will try to accomodate you.
  </p>

</div>

<ul class="clear">
  <li class="push-16 inline_menu">
    <%= link_to 'List Accelerators', accelerators_path %>
  </li>
</ul>

</div>