config/routes.rb
Accelr8::Application.routes.draw do

  resources :accelerators do
  end
  match 'accelerators/terms' => 'accelerators#terms', :via => :post
  match '/home' => 'accelerators#home', :as => 'home'

  devise_for :accelerator_users
  devise_for :users

  match '/accelerator_user_root', :to => 'accelerators#index'
  match '/accelerators' => 'accelerators#index', :as => :accelerator_user_root

  match '/user_root', :to => 'accelerators#index'

  match '/about' => 'acpages#about', :as => 'about'
  match '/beta' => 'acpages#beta', :as => 'beta'

  resources :questionnaires do
    resources :qfounders
    member do
      get 'apply'
    end
  end

  resources :ac_registrations, :only => [:index]
  match 'ac_registrations/testemail' => 'ac_registrations#testemail', :via => :post
  match 'ac_registrations/createbatch' => 'ac_registrations#createbatch', :via => :post
  match 'ac_registrations/destroybatch' => 'ac_registrations#destroybatch', :via => :delete

  root :to => "accelerators#home"

end

app/models/accelerator_user.rb
class AcceleratorUser < ActiveRecord::Base
  has_one :accelerator, :dependent => :destroy

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  # also :recoverable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :name, :password, :password_confirmation, :remember_me

  validates :name, 	:presence => true,
			:uniqueness => true
# seems to validate :email automatically using devise
# validates :email, 	:presence => true,
#			:uniqueness => true
end

app/views/accelerator_users/shared/_links.erb
<% if controller_name != 'sessions' %>
  <%= link_to "Accelerator Login", new_session_path(resource_name), :class => "right" %><br />
<% end %>

<% if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Create New Accelerator Login", new_registration_path(resource_name), :class => "right" %>
<% end %>

<% if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), :class => "right" %><br />
<% end %>

<% if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name), :class => "right" %><br />
<% end %>

<% if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name), :class => "right" %><br />
<% end %>

<% if devise_mapping.omniauthable? %>
  <% resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider), :class => "right" %><br />
  <% end %>
<% end %>

app/views/accelerator_users/shared/_login.html.erb
<div class="clear">
  <% if ! accelerator_user_signed_in? %>
    <%= link_to "Accelerator Login", new_accelerator_user_session_path, :title => "Add / Edit Accelerator Directory" %>
  <%# else %>
    <%#= link_to "Edit Accelerator Login Account", edit_accelerator_user_registration_path %>
  <% end %>
</div>

app/views/accelerator_users/shared/_logout.html.erb
<div class="push-1 span-9 last mediumfont">
  <% if accelerator_user_signed_in? %>
    <%= current_accelerator_user.name %> accelerator 
    <%= link_to "logged in.", edit_accelerator_user_registration_path, :title => "Edit accelerator login" %>
    Not you?
    <%= link_to "Log out", destroy_accelerator_user_session_path, :method => :delete %>
  <% end %>
</div>

<div class="clear"></div>
<% flash.each do |name, msg| %>
  <% if [:notice, :alert].include?(name) %>
    <%= content_tag :div, msg %>
  <% end %>
<% end %>
<br/>

app/views/accelerator_users/shared/_notices.html.erb
<p><%= notice %></p>
<p><%= alert %></p>