config/routes.rb
Accelr8::Application.routes.draw do

  resources :accelerators do
  end
  match 'accelerators/terms' => 'accelerators#terms', :via => :post
  match '/home' => 'accelerators#home', :as => 'home'

  devise_for :accelerator_users
  devise_for :users

  match '/accelerator_user_root', :to => 'accelerators#index'
  match '/accelerators' => 'accelerators#index', :as => :accelerator_user_root

  match '/user_root', :to => 'accelerators#index'

  match '/about' => 'acpages#about', :as => 'about'
  match '/beta' => 'acpages#beta', :as => 'beta'

  resources :questionnaires do
    resources :qfounders
    member do
      get 'apply'
    end
  end

  resources :ac_registrations, :only => [:index]
  match 'ac_registrations/testemail' => 'ac_registrations#testemail', :via => :post
  match 'ac_registrations/createbatch' => 'ac_registrations#createbatch', :via => :post
  match 'ac_registrations/destroybatch' => 'ac_registrations#destroybatch', :via => :delete

  root :to => "accelerators#home"

end

app/models/questionnaire.rb
class Questionnaire < ActiveRecord::Base
  has_many :ac_registrations, :dependent => :destroy
  has_many :qfounders, :dependent => :destroy  # :autosave => true
  belongs_to :user

  MAXLEN = 500

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  attr_accessible :firstname, :lastname, :email, :companyname, :website, :webvideo, :description, :businessplan, :team, :competition, :other, :invest, :advisor

  validates :companyname, 	:presence => true
  validates :lastname, 		:presence => true
  validates :email, 		:format => { :with => email_regex }
# validates :website, 		:format => /http/
# validates :webvideo, 		:format => /http/
  validates :description, 	:presence => true, 
				:length => { :maximum => MAXLEN }
  validates :businessplan, 	:length => { :maximum => MAXLEN }
  validates :competition, 	:length => { :maximum => MAXLEN }
  validates :team, 		:length => { :maximum => MAXLEN }
  validates :other, 		:length => { :maximum => MAXLEN }
  validates :invest, 		:length => { :maximum => MAXLEN }
  validates :advisor, 		:length => { :maximum => MAXLEN }

# validates_numericality_of :qfounder_ids, :greater_than => 0
# validates :qfounder_ids, 	:length => { :minimum => 1 }
# validates_presence_of 	:qfounder_ids
# validates_presence_of 	:qfounders
# validates_presence_of 	:qfounders.first
# validates :qfounder_ids, 	:presence => true
# validates :qfounders, 	:presence => true
# validates_associated  :qfounders
# validates_associated  :qfounders,	:presence => :true

  validate :has_a_qfounder

  def has_a_qfounder
#   if self.qfounder.nil?  # tests if any associated objects
    if self.qfounders.size < 1
      errors.add("Need", "at least one Founder with first or last name")
#     errors.add("Founders", "must have at least one entry with first or last name")
    end
  end

  def to_s
    self.companyname
  end
end

app/controllers/questionnaires_controller.rb
class QuestionnairesController < ApplicationController
  before_filter :authenticate_user!

  # GET /questionnaires
  # GET /questionnaires.xml
  def index
    @questionnaires = Questionnaire.all
#   @questionnaires = User.questionnaire.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @questionnaires }
    end
  end

  # GET /questionnaires/1
  # GET /questionnaires/1.xml
  def show
    @questionnaire = Questionnaire.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @questionnaire }
    end
  end

  # GET /questionnaires/1
  # GET /questionnaires/1.xml
  def apply
# used by accelerator/_list.html.erb

    @questionnaire = Questionnaire.find(params[:id])

    @sortcolumn = params[:column] ||= "startdate"
    @sortorder = params[:order] ||= "ASC"
    # sort columns by param
#   only show Accelerators that accept FH applications, by sort column order
#   @accelerators = Accelerator.where(:acceptapp => "Yes").order(@sortcolumn+" "+@sortorder)
    @accelerators = Accelerator.order(@sortcolumn+" "+@sortorder)

    respond_to do |format|
      format.html # apply.html.erb
      format.xml  { render :xml => @questionnaire }
#     flash[:notice] = params.inspect
    end
  end

  # GET /questionnaires/new
  # GET /questionnaires/new.xml
  def new
    @questionnaire = Questionnaire.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @questionnaire }
    end
  end

  # GET /questionnaires/1/edit
  def edit
    @questionnaire = Questionnaire.find(params[:id])
  end

  # POST /questionnaires
  # POST /questionnaires.xml
  def create
    @questionnaire = Questionnaire.new(params[:questionnaire])
#   @questionnaire.user_id = User.find(?)
    @questionnaire.user_id = current_user.id

#   if !Qfounder.params_any?(params['qfounder'])
    if !params['qfounder'].nil? && params['qfounder'].any?
      params['qfounder'].each { |k, fdr|
        if Qfounder.new(fdr).valid?
          @questionnaire.qfounders.build(fdr)
        end
      }
    end  # !params['q'].nil?

    respond_to do |format|
#     @questionnaire.valid?
#     if @questionnaire.errors.empty?
      if @questionnaire.save  # also saves qfounders using build()
        format.html { redirect_to(@questionnaire) }
#       flash[:notice] = 'Accelerator Application was successfully created.'
#       format.html { render :action => "show" }
        format.xml  { render :xml => @questionnaire, :status => :created, :location => @questionnaire }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @questionnaire.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /questionnaires/1
  # PUT /questionnaires/1.xml
  def update
    @questionnaire = Questionnaire.find(params[:id])

#   oldfounders = @questionnaire.qfounders  # dynamic memory, build adds to it
    oldfounders = []
    @questionnaire.qfounders.each { |f| oldfounders << f } # not dynamic memory

#   if !Qfounder.params_any?(params['qfounder'])
    if !params['qfounder'].nil? && params['qfounder'].any?
      params['qfounder'].each { |k, fdr|
#       if Qfounder.has_params?(fdr)
        qfdr = Qfounder.new(fdr)
        if qfdr.valid?
          ffdr = qfdr.member_of(oldfounders)
          if !ffdr.nil?  # rm from oldfounders if already exists
            oldfounders.delete(ffdr)
          else  # build only if fdr params changed
            @questionnaire.qfounders.build(fdr)
          end
        end  # qfdr.valid?
      }    # params['q'].each
    end  # !params['q'].nil?

#   delete remaining oldfounders
    @questionnaire.qfounders.delete(oldfounders)

    respond_to do |format|
      if @questionnaire.update_attributes(params[:questionnaire])
#       flash[:notice] = 'Application was successfully updated.'
#       format.html { redirect_to(apply_questionnaire_path(@questionnaire)) }
        format.html { render :action => "show" }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @questionnaire.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /questionnaires/1
  # DELETE /questionnaires/1.xml
  def destroy
    @questionnaire = Questionnaire.find(params[:id])
    @questionnaire.destroy  # also destroys associated qfounders

# flips to accel index.html, should flip to ques new.html?
    respond_to do |format|
#     format.html { redirect_to new_questionnaire_path }
      format.html { redirect_to accelerators_path }
      format.xml  { head :ok }
    end
  end
end

app/helpers/questionnaires_helper.rb
module QuestionnairesHelper
end

app/views/questionnaires/_form.html.erb
<% if @questionnaire.new_record? %>
  <% @questionnaire.qfounders.build %> <!-- makes three qfounders -->
  <% @questionnaire.qfounders.build %>
  <% @questionnaire.qfounders.build %>
<% else %>
  <% if (@questionnaire.qfounders.size < 10) %>
    <% @questionnaire.qfounders.build %> <!-- makes one qfounder -->
  <% end %>
<% end %>

<p id="notice"><b class="required"><%= notice %></b></p>

<%= form_for @questionnaire do |f| %>
  <% if @questionnaire.errors.any? %>
    <div id="error_explanation" class="clear">
      <h3 class="required"><%= pluralize(@questionnaire.errors.count, "error") %> prohibited this application from being saved:</h3>

      <ul>
      <% @questionnaire.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset class="accel-form nomargin clear span-22 last">
    <legend>Company Information</legend>
    <table class="clear span-22 last">
      <tr class="nomargin no_stripe">
        <td><b class="nowrap">Company Name:</b><span class="required">*</span></td>
        <td colspan=4><%= f.text_field :companyname, :size => 80 %></td>
      </tr>
      <tr class="nomargin no_stripe">
        <td class="nowrap"><%= f.label :website, "Website (if any)" %></td>
        <td colspan=4><%= f.text_field :website, :size => 80 %></td>
      </tr>
      <tr class="nomargin no_stripe">
        <td class="nowrap">
          <b>Primary Contact:</b><span class="required">*</span>
        </td>
        <td class="nowrap"><%= f.label :firstname, "First name" %></td>
        <td>
          <%= f.text_field :firstname, :size => 23 %>
        </td>
        <td class="nowrap"><%= f.label :lastname, "Last name" %></td>
        <td>
          <%= f.text_field :lastname, :size => 23 %>
        </td>
      </tr>
      <tr class="nomargin no_stripe">
        <td/>
        <td><%= f.label :email %></td>
        <td colspan=3><%= f.text_field :email, :size => 70 %></td>
      </tr>
    </table>
  </fieldset>

  <br/>
  <%= render :partial => 'qfounders/form', :locals => {:form => f} %>
  <% textboxclass = "span-15 charcount maxchar" + Questionnaire::MAXLEN.to_s %>

<fieldset class="accel-form nomargin clear span-22 last">
<legend>Questionnaire</legend>
  <table class="clear span-22 last">
    <tr class="no_stripe">
      <td class="addpad"><b>
        <%= f.label :team, "Can you tell us about the founders team background?" %>
      </b></td>
    </tr>
    <tr class="no_stripe">
      <td>
        <%= f.text_area :team, :id => "team", :class => textboxclass %>
<!-- 6 x 80 seems to be 6 x 55, try 6 x 120 => 6 x 82.5 ...
     huh! value of :cols is ignored!  -->
      </td>
      <td class="nomargin"><span id="team_ct" class="span-4 small ctpad"></span>
      </td>
    </tr>
    <tr class="no_stripe">
      <td class="addpad"><b class="nowrap">
        <%= f.label :description, "Please describe your company or project in 2-3 sentences." %><span class="required">*</span>
      </b></td>
      <td/>
    </tr>
    <tr class="no_stripe">
      <td>
        <%#= f.text_area :description, :rows => 6, :cols => 80 %>
        <%= f.text_area :description, :id => "describe", :class => textboxclass %>
      </td>
      <td>
        <span id="describe_ct" class="span-4 small ctpad"></span>
      </td>
    </tr>
    <tr class="no_stripe">
      <td class="addpad">
        <b><%= f.label :webvideo, "You may also submit a web video describing your company or project." %></b>
        <br/><%= f.text_field :webvideo, :size => 65 %>
      </td>
      <td>
        <br/>
        <span class="span-6 small addpad">Please keep video under 2 minutes.</span>
      </td>
    </tr>
    <tr class="no_stripe">
      <td class="addpad"><b>
        <%= f.label :businessplan, "Please describe your business plan, customer base, and potential revenue stream." %>
      </b></td>
    </tr>
    <tr class="no_stripe">
      <td>
        <%= f.text_area :businessplan, :id => "business", :class => textboxclass %>
      </td>
      <td class="nomargin"><span id="business_ct" class="span-4 small ctpad"></span>
      </td>
    </tr>
    <tr class="no_stripe">
      <td class="addpad"><b>
        <%= f.label :competition, "Who are your competitors, if any, and how your product is different from theirs?" %>
      </b></td>
    </tr>
    <tr class="no_stripe">
      <td>
        <%#= f.text_area :competition, :rows => 6, :cols => 80 %>
        <%= f.text_area :competition, :id => "comp", :class => textboxclass %>
      </td>
      <td class="nomargin"><span id="comp_ct" class="span-4 small ctpad"></span>
      </td>
    </tr>
    <tr class="no_stripe">
      <td class="addpad"><b>
        <%= f.label :other, "If the founders have contributed to other significant projects, please describe." %>
      </b></td>
    </tr>
    <tr class="no_stripe">
      <td>
        <%= f.text_area :other, :id => "other", :class => textboxclass %>
      </td>
      <td class="nomargin"><span id="other_ct" class="span-4 small ctpad"></span>
      </td>
    </tr>
    <tr class="no_stripe">
      <td class="addpad"><b>
        <%= f.label :invest, "If you have any investors, please describe." %>
      </b></td>
    </tr>
    <tr class="no_stripe">
      <td>
        <%= f.text_area :invest, :id => "invest", :class => textboxclass %>
      </td>
      <td class="nomargin"><span id="invest_ct" class="span-4 small ctpad"></span>
      </td>
    </tr>
    <tr class="no_stripe">
      <td class="addpad"><b>
        <%= f.label :advisor, "If you have advisors or mentors working with you, please describe." %>
      </b></td>
    </tr>
    <tr class="no_stripe">
      <td>
        <%= f.text_area :advisor, :id => "advisor", :class => textboxclass %>
      </td>
      <td class="nomargin"><span id="advisor_ct" class="span-4 small ctpad"></span>
      </td>
    </tr>
  </table>
</fieldset>

  <br/>
  <div class="actions span-6">
    <% if @questionnaire.new_record? %>
      <%= f.submit value='Create New Accelerator Application' %>
    <% else %>
      <%= f.submit value='Update Accelerator Application' %>
    <% end %>
  </div>
<% end %>

app/views/questionnaires/apply.html.erb
<!-- use a div or span? -->
<!--div class="right span-7 applybox applycolor round">
  <span class="nostyle mediumfont">
    <b><i>To apply to accelerators:</i></b>
  </span>
  <fieldset class="applybox round">
    <ul class="mediumfont">
      <li>
        Select <b>Apply Now</b> for accelerators you are interested in.
      </li>
      <li>
        Click <b>Submit Application</b> to email your application.
      </li>
    <ul>
  </fieldset>
</div!-->

<ul class="right span-6 applybox applycolor">
  <li class="nostyle ">
    <b><i>To apply to accelerators:</i></b>
  </li>
  <!--fieldset class="applybox round"!-->
  <!--li class="nostyle mediumfont">
    Select <b>Apply Now</b> for accelerators you are interested in, then click <b>Submit Application</b> to email your application.
  </li!-->
  <li class="nostyle mediumfont">
    <ul>
      <li>
        Select <b>Apply Now</b> for accelerators you are interested in.
      </li>
      <li>
        Click <b>Submit Application</b> to email your application.
      </li>
    </ul>
  </li>
  <!--/fieldset!-->
</ul>

<ul class="span-15 applybox applycolor round">
  <fieldset class="applybox round">
    <legend><b><i>Accelerator Application</i></b></legend>
    <li class="nostyle">
      <span class="span-4"><b>Company Name:</b></span>
      <span class="span-10 last"><%= @questionnaire.companyname %></span>
    </li>
    <li class="nostyle">
      <span class="span-4"><b>Founders:</b></span>
      <span class="span-10 last"><%= @questionnaire.qfounders.map { |t| t.firstname + " " + t.lastname }.join(", ") %></span>
    </li>
    <li class="nostyle">
      <span class="span-4 prepend-1 mediumfont">
        <%= link_to 'View Application Details', @questionnaire %>
      </span>
      <span class="span-4 mediumfont last right">
        <%#= link_to 'Email Test Application', '#', :title => "Email a Test Application to Founders" %>
      </span>
    </li>
  </fieldset>
</ul>

<!--ul class="span-14 applybox round">
  <li class="nostyle bigfont">
    <b><i>Accelerator Application</i></b>
  </li>
  <li class="nostyle">
    <span class="span-4"><b>Company Name:</b></span>
    <span class="span-8 last"><%#= @questionnaire.companyname %></span>
  </li>
  <li class="nostyle">
    <span class="span-4"><b>Founders:</b></span>
    <span class="span-8 last"><%#= @questionnaire.qfounders.map { |t| t.firstname + " " + t.lastname }.join(", ") %></span>
  </li>
  <li class="nostyle">
    <span class="span-6 prepend-1 mediumfont">
      <%#= link_to 'View Application Details', @questionnaire %>
    </span>
  </li>
  <li class="nostyle">
    <%#= link_to 'Email Test Application', '#', :title => "Email a Test Application to Founders" %>
  </li>
</ul!-->

<br class="last clear"/>
<span id="notice" class="clear"><i><%= notice %></i></span>

<br class="last clear"/>

<%= render :partial => 'accelerators/list' %>

<ul class="accel">
  <li class="nostyle">
    <%= link_to 'Back to Accelerator List', accelerators_path %>
  </li>
</ul>

app/views/questionnaires/edit.html.erb
<div class="span-20">

<h4><b>Update Accelerator Application</b></h4>

<%= render 'form' %>

<ul class="push-7">
  <li class="inline_menu span-4">
    <%= link_to 'Discard Changes', @questionnaire %>
  </li>
  <li class="inline_menu span-4">
    <%= link_to 'Delete Application', questionnaire_path(@questionnaire), :confirm => 'Are you sure you want to delete this application?', :method => :delete %>
  </li>
</ul>

</div>

app/views/questionnaires/index.html.erb
<h4><b>List of Accelerator Applications</b></h4>

<ul class="accel small">
  <li class="nostyle span-19 last">
    Accelerator applications may be used to apply to accelerator programs.  A founder may create multiple applications for each company or project.  By default, the last application is used.
  </li>
  <li class="clear left_margin">
    Click on Edit to view an application and edit its details.
  </li>
  <li class="left_margin">
    Click on Apply to use an application to apply to accelerators.
  </li>
  <li class="left_margin">
    Click on Create New Accelerator Application to start a new application.
  </li>
</ul>
<br/>

<% if @questionnaires.any? %>
  <table class="accel">
    <tr>
      <th class="index">Company Name</th>
      <th class="index">Website</th>
      <th class="index">Contact Email</th>
      <th class="index">Founders</th>
      <th class="index">Description</th>
      <th class="index">Web Video</th>
      <th class="index center">Edit</th>
      <th class="index center">Apply to<br/>Accelerators</th>
    </tr>

    <% @questionnaires.each do |questionnaire| %>
    <tr>
      <td class="index"><%= questionnaire.companyname %></td>
      <td class="index"><%= link_to questionnaire.website, questionnaire.website, :target => "_blank" %></td>
      <td class="index"><%= questionnaire.email %></td>
      <td class="index">
        <%#= questionnaire.qfounders.map { |t| t.firstname + " " + t.lastname }.join(", ") %>
        <% if questionnaire.qfounders.any? %>
          <%= questionnaire.qfounders.map { |t| t.lastname }.join(", ") %>
        <% else %>
          <span class="required">None</span>
        <% end %>
      </td>
      <td class="index description">
        <div class="info round"><%= questionnaire.description %></div>
      </td>
      <td class="index">
        <% if (questionnaire.webvideo.nil? || questionnaire.webvideo.empty?) %>
           None
        <% else %>
          <%= link_to questionnaire.webvideo, questionnaire.webvideo, :target => "_blank" %>
        <% end %>
      </td>
      <td class="index center">
        <%= button_to 'Edit', { :controller => "questionnaires", :action => "edit", :id => questionnaire.id }, :method => :get, :class => "small" %>
      </td>
      <td class="index center">
        <% if questionnaire.qfounders.any? %>
          <%= button_to 'Apply', { :controller => "questionnaires", :action => "apply", :id => questionnaire.id }, :method => :get, :class => "small" %>
        <% else %>
          <%= button_to 'Apply', { :controller => "questionnaires", :action => "apply", :id => questionnaire.id }, :method => :get, :class => "small", :disabled => :true %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </table>
<% end %>

<ul class="accel">
  <li class="nostyle">
    <%= button_to 'Create New Accelerator Application', { :controller => "questionnaires", :action => "new" }, :method => :get %>
  </li>
</ul>

app/views/questionnaires/new.html.erb
<div class="span-20">

<h4><b>New Accelerator Application</b></h4>

<%= render 'form' %>

<ul class="push-12">
  <li class="inline_menu span-4">
    <%= link_to 'Discard Changes', accelerators_path %>
  </li>
</ul>

</div>

app/views/questionnaires/show.html.erb
<%= button_to 'Apply to Accelerators', { :controller => "questionnaires", :action => "apply", :id => @questionnaire }, :method => :get, :class => "bigbutton right" %>

<h4><b>Accelerator Application Details</b></h4>

<p id="notice"><%= notice %></p>

<fieldset class="accel-form nomargin">
  <legend>Company Information</legend>
  <table class="accel span-20">
    <tr class="nomargin no_stripe">
      <td><br/></td>
    </tr>
    <tr class="nomargin no_stripe">
      <td class="span-4"><b>Company Name:</b></td>
      <td class="span-16 last clear">
        <%= @questionnaire.companyname %>
      </td>
      <td/>
      <td>
        <%= form_for :ac_registration, :url => { :action => 'testemail', :controller => 'ac_registrations' } do |f| %>
          <% quid = nil %>
          <% if ! @questionnaire.nil? %>
            <% quid = @questionnaire.id %>
          <% end %>
          <%= hidden_field_tag 'quid', quid %>
          <%= f.submit value='Email Test Application', :class => "right", :title => "Email test application" %>
        <% end %>
      </td>
    </tr>
    <tr class="nomargin no_stripe">
      <td><br/></td>
    </tr>
    <tr class="nomargin no_stripe">
      <td class="span-4"><b>Website:</b></td>
      <td class="span-16 last clear">
        <% if (@questionnaire.website.nil? || @questionnaire.website.empty?) %>
           None
        <% else %>
          <%= link_to @questionnaire.website, @questionnaire.website, :target => "_blank" %>
        <% end %>
      </td>
      <td/>
    </tr>
  </table>
  <table class="accel span-20">
    <tr class="nomargin no_stripe">
      <td class="span-4"><b>Contact:</b></td>
      <td class="span-2">Name:</td>
      <td class="span-14 last clear"><%= @questionnaire.firstname + " " + @questionnaire.lastname %></td>
    </tr>
    <tr class="nomargin no_stripe">
      <td class="span-4"/>
      <td class="span-2">Email:</td>
      <td class="span-14 last clear"><%= @questionnaire.email %></td>
    </tr>
  </table>
</fieldset>

<%= render :partial => "qfounders/list" %>

<fieldset class="accel-form nomargin">
  <legend>Questionnaire</legend>
  <br/>

  <p class="span-18 last">
    <b>Founder Team Background:</b>
    <%= @questionnaire.team %>
  </p>

  <p class="span-18 last">
    <b>Description:</b>
    <%= @questionnaire.description %>
  </p>

  <p class="span-18 last">
    <b>Web Video:</b>
    <% if (@questionnaire.webvideo.nil? || @questionnaire.webvideo.empty?) %>
       None
    <% else %>
      <%= link_to @questionnaire.webvideo, @questionnaire.webvideo, :target => "_blank" %>
    <% end %>
  </p>

  <p class="span-18 last">
    <b>Business Plan:</b>
    <%= @questionnaire.businessplan %>
  </p>

  <p class="span-18 last">
    <b>Competition:</b>
    <%= @questionnaire.competition %>
  </p>

  <p class="span-18 last">
    <b>Other Founder Projects:</b>
    <%= @questionnaire.other %>
  </p>

  <p class="span-18 last">
    <b>Investors:</b>
    <%= @questionnaire.invest %>
  </p>

  <p class="span-18 last">
    <b>Advisors / Mentors:</b>
    <%= @questionnaire.advisor %>
  </p>
</fieldset>

<div class="last clear"/>
  <br/>
  <%= button_to 'Edit Application', { :controller => "questionnaires", :action => "edit", :id => @questionnaire }, :method => :get %>
</div>