config/routes.rb
Accelr8::Application.routes.draw do

  resources :accelerators do
  end
  match 'accelerators/terms' => 'accelerators#terms', :via => :post
  match '/home' => 'accelerators#home', :as => 'home'

  devise_for :accelerator_users
  devise_for :users

  match '/accelerator_user_root', :to => 'accelerators#index'
  match '/accelerators' => 'accelerators#index', :as => :accelerator_user_root

  match '/user_root', :to => 'accelerators#index'

  match '/about' => 'acpages#about', :as => 'about'
  match '/beta' => 'acpages#beta', :as => 'beta'

  resources :questionnaires do
    resources :qfounders
    member do
      get 'apply'
    end
  end

  resources :ac_registrations, :only => [:index]
  match 'ac_registrations/testemail' => 'ac_registrations#testemail', :via => :post
  match 'ac_registrations/createbatch' => 'ac_registrations#createbatch', :via => :post
  match 'ac_registrations/destroybatch' => 'ac_registrations#destroybatch', :via => :delete

  root :to => "accelerators#home"

end

app/views/layouts/_footer.html.erb
<footer>
  <section>
    <ul>
      <li>
        <h3>Founders<span class='dblue'>Hookup</span></h3>
        <p><%= link_to "Click here", "http://www.foundershookup.com", :target => "_blank", :class => "footer_link" %>
            to go to the official Founders Hookup web site.
        </p>
        <p> &copy; 2011 FoundersHookup.Inc. <br/>
        All rights reserved.  <br/>
        </p>
      </li>

      <li>
        <h3>Site</h3>
        <ul style='padding-left: 0px !important;'>
          <li><%= link_to "Home", root_path, :class => 'footer_desc' %></li>
          <li><%= link_to "About Us", about_path, :class => 'footer_desc' %></li>
          <li><%= link_to "Beta Test", beta_path, :class => 'footer_desc' %></li>
          <li><%= link_to "Contact Us", about_path+"#contact", :class => 'footer_desc' %></li>
        </ul>
      </li>
      
      <li>
        <h3>Follow Us</h3>
        <p href='#'>
          <img src="images/ideaware/icn/icn_fb.png" alt="Facebook" />
          <img src="images/ideaware/icn/icn_tw.png" alt="Twitter" />
        </p>
        <br/>
      </li>
				
      <li class="last">
        <h3>Contact Us</h3>
        <a class='footer_desc' href="mailto:support@foundershookup.com">support@foundershookup.com</a>
          <span class='footer_desc'>
            <strong>FoundersHookup, Inc.</strong> <br />
  					660 4th Street #487 <br />
  					San Francisco, CA 94107 <br />
            Phone: +1-415-309-8860
          </span>
      </li>
    </ul>
  </section>
</footer>

app/views/layouts/_header.html.erb
<header> 

  <div style='width: 960px; margin: 0 auto;'>
    <% logo = image_tag("ideaware/misc/fh_logo.png", :alt => "Founders Hookup", 
                        :class => "fh_logo") %>
    <%= link_to logo, root_path %>

    <nav>
    <% if user_signed_in? %>
      <table border='0' style='background-color: transparent; margin: 0; padding: 0; display: inline;'>
        <tr style='background-color: transparent;'>
          <td class='signin_row'>
            <span class='header_username'>
              User: <%= current_user.email %>
            </span>
          </td>
          <td class='signin_row' rowspan='2'>
      <%#= image_tag "#{@_current_user.photo_url}", :alt => "#{@_current_user.given_name} #{@_current_user.surname}", :size => "40x40", :style => "display: inline; padding: 0;" %>
          </td>
        </tr>

        <tr style='background-color: transparent;'>
          <td class='signin_row'>
            <ul>
              <% unless controller_name == "registrations" %>
                <li><%= link_to "Edit User", edit_user_registration_path %></li>
              <% end %>
              <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
              <li><%= link_to "About", about_path %></li>
            </ul>
          </td>
        </tr>
      </table>

    <% else %>
      <ul>
        <li><%= link_to "User Sign In", new_user_session_path %></li>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>
    <% end %>
  </nav>

  <h2 class="header_test">
    <%= link_to "Accelerator Beta Test", beta_path, :class => "header_test" %>
  </h2>

  </div> 
</header>

app/views/layouts/_nav.html.erb
<div style='clear: both; height: 0px;'>&nbsp;</div>
<%# if user_signed_in? %>
<% if !( !user_signed_in? || (controller_name=='registrations' && action_name=='edit') ) %>
  <ul id="navbar">
    <li><%= link_to "Browse Profiles", "#" %></li>
    <li><%= link_to "Rank Candidates", "#" %></li>
    <li><%= link_to "My Profile", "#" %></li>
    <li><%= link_to "Accelerators", accelerators_path %></li>
    <li><%= link_to "Events", '#' %></li>
    <li><%= link_to "Wisdom", '#' %></li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Accelr8</title>
  <%#= stylesheet_link_tag :all %>
  <%#= stylesheet_link_tag 'scaffold' %>
  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
  <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
  <!--[if lt IE 8]>
    <%= stylesheet_link_tag 'blueprint/ie', :media => 'screen, projection' %>
  <![endif]-->
  <%= stylesheet_link_tag 'custom',  :media => 'screen' %>
  <%= stylesheet_link_tag 'accel',   :media => 'screen' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <%= render 'layouts/header' %>

  <div class="container">
    <%= render 'layouts/nav' %>
    <section>
    <!--section style="background:#cdf;"!-->
    <!--section style="background:#ede;"!-->
      <%= yield %>
    </section>
  </div>

  <%= render 'layouts/footer' %>
</body>
</html>